---
title: "Create and Attribute Source of Variables in Example File"
date: "2023-02-09 <br> Updated: `r Sys.Date()"
---

# Overview

This is an example file to assess source attributes needed for Link2Care Codebook.

# Create first dataframe
```{r}
age <- c("52", "43")
date_of_birth <- c("1971-08-09", "1980-03-05")
race_eth <- c("AA", "W")
weight <- c("168", "210")
height <- c("175", "163")
visits_attended <- c("2", "4")

df1 <- data.frame (age, date_of_birth, race_eth, weight, height, visits_attended)

print(df1)
```


# Create second dataframe
```{r}

identifier <- c("3810", "3875")
age <- c("52", "43")
race_eth <- c("AA", "W")
drawing <- c("Yes", "No")
housing <- c("Sometimes", "Never")

df2 <- data.frame (identifier, age, race_eth, drawing, housing)

print(df2)
```


# Create third dataframe
```{r}

race_eth <- c("AA", "W")
food_stamps <- c("Difficult", "Sometimes Difficult")
reading <- c("Comfortable", "Comfortable")
housing <- c("Sometimes", "Never")
times_unhoused <- c("4", "1")

df3 <- data.frame (race_eth, food_stamps, reading, housing, times_unhoused)

print(df3)
```
# Merge dataframes and find source attributes

```{r}

library(haven)
library(codebookr)
library(dplyr)

df1_att <- cb_add_col_attributes(df1, source())
df2_att <- cb_add_col_attributes(df2, source())
df3_att <- cb_add_col_attributes(df3, source())

print(df1_att)
print(df2_att)
print(df3_att)




```

# Utilize source attribute adding function to add to source attributes present

```{r}

add_source_attr <- function(.df1_att, source){
  df_nm <- deparse(substitute(.df1_att))
  for (name in names(.df1_att)) {
    attr(.df1_att[[name]], "source") <- source
  }
  assign(df_nm, .df1_att, envir = .GlobalEnv)
}

add_source_attr <- function(.df2_att, source){
  df_nm <- deparse(substitute(.df2_att))
  for (name in names(.df2_att)) {
    attr(.df2_att[[name]], "source") <- source
  }
  assign(df_nm, .df2_att, envir = .GlobalEnv)
}


add_source_attr <- function(.df3_att, source){
  df_nm <- deparse(substitute(.df3_att))
  for (name in names(.df3_att)) {
    attr(.df3_att[[name]], "source") <- source
  }
  assign(df_nm, .df3_att, envir = .GlobalEnv)
}

attributes(df1_att)
attributes(df2_att)
attributes(df3_att)
```


