---
title: "Combined Participant Data Variable Labels"
---


```{r}
label <- function(col, label) {
  df <- get("combined_participant_data", envir = .GlobalEnv)
  attributes(df[[col]])$label <- label
  assign("combined_participant_data", df, envir = .GlobalEnv)
}
```


```{r}
label("id", "Subject ID")
label("date_visit", "Today's date")
label("group", "What is the participant's treatment group?")
label("ml_status","Master log status")
label("ml_group", "Master log group")
label("ml_name_first", "First name")
label("ml_name_last","Last name")
label("ml_name_middle_init","Middle name")
label("ml_gender","Master log gender")
label("ml_race","Master log race")
label("ml_hispanic","Master log hispanic")
label("ml_date_birth","Master log date of birth")
label("ml_age","Master log age")
label("ml_clincard_id","ClinCard ID")
label("ml_n_clincards","N clinicard distributed")
label("ml_phone_id","Phone ID")
label("ml_phone_number_l2c","L2C phone number")
label("ml_phone_n_distributed", "N phone distributed")
label("ml_care_manager","Care manager")
label("ml_v1","Visit 1 attended")
label("ml_v2","Visit 2 attended")
label("ml_v3","Visit 3 attended")
label("ml_v4","Visit 4 attended")
label("ml_v5","Visit 5 attended")
label("ml_v3_r_distributed","Redcap visit 3 distributed")
label("ml_v3_r_completed","Redcap visit 3 completed")
label("ml_v4_r_distributed","Redcap visit 4 distributed")
label("ml_v4_r_completed","Redcap visit 4 completed")
label("ml_v5_r_distributed","Redcap visit 5 distributed")
label("ml_v5_r_completed","Redcap visit 5 completed")
label("ii","Interviewer Initials")

#screnning questions
label("sq_age","What is your age?")
label("sq_7a","How long ago were you released from the jail?")
label("sq_7c","Other form of evidence of recent incarceration in Dallas Country Jail?")
label("sq_9l","Homeless shelters name:")
label("sq_18","Which of the following forms of media do you use?")
label("sq_22","Which of the following forms of identification do you possess?")

#mini-mental exam
label("mms_1","Score for MMS_1")
label("mms_2","Score for MMS_2")
label("mms_3","Word recall")
label("mms_recall_1","Word recall score")
label("mms_4","Ask the individual to count backwards from 100 by 7's")
label("mms_count","Number count")
label("mms_5","Please spell the word WORLD backwards")
label("mms_num","Number count 2")
label("mms_6","Earlier I told you three words. Can you name all three words?")
label("mms_recall_2","Word recall score 2 ")
label("mms_7","I am going to point to an object and ask you to name the objects")
label("mms_object","NAMING OBJECTS")
label("mms_9","Give the individual a piece of paper and ask the them to: 1) Hold the paper in their right hand 2) Fold the paper in half. 3) Put the paper on the floor.")
label("mms_paper","FOLDING PAPER")
label("mms_s","Mini Mental State Exam Score")

#realm card
label("realm","Realm")
label("realm_total","Realm total")


label("ctime","Current time")

#demographics
label("dem_race_mult_n","You have stated that you have more than one race. Please look at the categories below and mark the ones that best describe your race (Check all that apply)")
label("dem_ins","Do you have health insurance? Please check all that apply.")
label("dem_social_security","Do you currently receive Social Security benefits?")
label("dem_snap_amount","What is the amount of food stamps (SNAP) do you get each month?")
label("dem_income_source","What are your sources of income? (Please check all that apply).")

#The Brief Homelessness Questionnaire
label("bh_1","What is the total amount of time you have been homeless in your lifetime? (for example 3 and a half years would be 3 years and 6 months)")
label("bh_1y","Years: What is the total amount of time you have been homeless in your lifetime? (for example 3 and a half years would be 3 years and 6 months)")
label("bh_1m","Months: What is the total amount of time you have been homeless in your lifetime? (for example 3 and a half years would be 3 years and 6 months)")
label("bh_1d","Days: What is the total amount of time you have been homeless in your lifetime? (for example 3 and a half years would be 3 years and 6 months)")
label("bh_3","How old were you the first time you became homeless?")
label("bh_4","How long ago did the current period of homelessness begin? (for example 3 years would be 3 years and 0 months)")
label("bh_4y","Years: How long ago did the current period of homelessness begin? (for example 3 years would be 3 years and 0 months)")
label("bh_4m","Months: How long ago did the current period of homelessness begin? (for example 3 years would be 3 years and 0 months)")
label("bh_4d","Days: How long ago did the current period of homelessness begin? (for example 3 years would be 3 years and 0 months)")
label("bh_7","How long have you been receiving services at the Bridge? (for example, 6 and a half months would be 2 weeks, 6 months, 0 years)")
label("bh_7y","Years: How long have you been receiving services at the Bridge? (for example, 6 and a half months would be 2 weeks, 6 months, 0 years)")
label("bh_7m","Months: How long have you been receiving services at the Bridge? (for example, 6 and a half months would be 2 weeks, 6 months, 0 years)")
label("bh_7w","Weeks: How long have you been receiving services at the Bridge? (for example, 6 and a half months would be 2 weeks, 6 months, 0 years)")
label("bh_11","On average, how many hours do you spend at shelters each day (counting sleep time)?")
label("bh_12","What are the reasons for your current homelessness (check all that apply)?	")
label("bh_13","Have you ever been arrested and booked for: (Check all that apply)")
label("bh_14","Were you arrested or booked for breaking the law in the PAST MONTH?")
label("bh_15","During your lifetime, how many separate times have you been to jail or prison?")
label("bh_17","During your lifetime, how much time have you spent in jail or prison?")
label("bh_18y","Years: During your most recent incarceration, how long were you in jail?")
label("bh_18m","Months: During your most recent incarceration, how long were you in jail?")
label("bh_18w","Weeks: During your most recent incarceration, how long were you in jail?")
label("bh_18d","Weeks: During your most recent incarceration, how long were you in jail?")


#Self-Rated Health Questionnaire
label("srh_7","Please select the Cardiovascular Diseases (heart/circulatory disease) that you have been diagnosed with. (Check all that apply)")
label("srh_8","Please select the Pulmonary Diseases (lung diseases) that you have been diagnosed with. (Check all that apply)")
label("srh_9","Please select the Cancers you have been diagnosed with? (Check all that apply)")
label("srh_14","Which of the following have you been diagnosed with? (Check all that apply)")
label("srh_18","I am currently taking medication for: (check all conditions for which you ARE taking medication)")
label("srh_24","I have a prescription for the following disorders: (check all that apply)")
label("srh_26","What were the reasons that you did not take your depression medication yesterday? (check all that apply)")
label("srh_28","What were the reasons that you did not take your Schizophrenia or Schizoaffective disorder medication yesterday? (check all that apply)")
label("srh_30","What were the reasons that you did not take your Bipolar Disorder medication yesterday? (check all that apply)")
label("srh_32","What were the reasons that you did not take your Anxiety Disorder medication yesterday? (check all that apply)")
label("srh_34","What were the reasons that you did not take your PTSD medication yesterday? (check all that apply)")
label("srh_38","Which Substance Use Disorder have you been diagnosed with? (check all that apply)")
label("srh_40","Please select all the substances that you used in the past 30 days.")
label("srh_52","What type of health related issue? (Check all types of smartphone apps that you have used)")

#Tobacco History Questionnaire
label("t_3","How long ago did you quit smoking? (for example 3 and a half years would be 3 years and 6 months)")
label("t_3y","Years: How long ago did you quit smoking? (for example 3 and a half years would be 3 years and 6 months)")
label("t_3m","Months: How long ago did you quit smoking? (for example 3 and a half years would be 3 years and 6 months)")
label("t_4","How many years were you a smoker")
label("t_9","How many years have you smoked?")
label("t_12","At what age did you begin smoking cigarettes or cigarillos?")
label("t_15","Which of the following have you used to help you quit smoking in the past (check all that apply)?")
label("t_24","Which of these would be the hardest thing about stopping smoking? (select all that apply)")
label("t_32","Which of the following products have you tried, even just one time (click all items that you have used in the past)?")
label("t_33","You reported that you have used e-cigarettes, vapes, or other vaping devices in the past. Which of these types of devices have you used?")
label("t_35","Which of the following products have you used in the past 30 days? (Click all items that you have used in the past 30 days).")
label("t_38","During an average weekday, how many smokers are you around?")
label("t_39","During an average weekend, how many smokers are you around")
label("t_40","How many close friends do you have? It is okay to count family members if you consider them your best friends.")
label("t_41","How many of these close friends smoke?")
label("t_42","How many of your 5 best friends smoke? It is okay to count family members if you consider them your best friends.")

#####
label("brs_2","On average, how many hours of sleep do you get in a 24-hour period? Think about the time you actually spend sleeping or napping, not just the amount of sleep you think you should get.")
label("af_drinks","Number of drinks based on gender")
label("sb_2","How old were you the first time you had any kind of sex, including vaginal, anal, or oral?")
label("sb_3","In the past 12 months, with how many people have you had any kind of sex?")
label("sb_7","Has a health care professional EVER told you that you had: (Please select all that apply)")
label("r_10","Over the past 30 days, how many days did you receive employment/job readiness training at local shelters?")
label("r_16","What types of services would be most helpful to you right now? (select all that apply)")
label("bpm_5","Which of the following would keep you from connecting to your case manager over the phone? (select all that apply)")
label("endtime","End Time")
label("etime","Elapsed interview/data entry time")


label("mms_score","Mini Mental Status Score")
label("mms_total","Mini Mental Status Total")


label("phq_dep_dicot_total","PHQ dichotomous total")
label("phqgad","PHQ generalized anxiety disorder")
label("hsi_bl","Heaviness of smoking index baseline")
label("pa","Physical aggression subscale")
label("va","Verbal aggression subscale")
label("a","Anger subscale")
label("ha","Hostility subscale")
label("aq","Agression subscale totals")
label("ces_5r","Reverse I felt hopeful scored")
label("ces_8r","Reverse I was happy scored")
label("ces_total","CES-D total: 1-10 (10 or greater is considered depressed")

#CES-D Dichotomus variables
label("ces_1_dichot","CES-D dichotomus:During the past week, I was bothered by things that don't usually bother me")
label("ces_2_dichot","CES-D dichotomus:During the past week, I had trouble keeping my mind on what I was doing.")
label("ces_3_dichot","CES-D dichotomus:During the past week, I felt depressed.")
label("ces_4_dichot","CES-D dichotomus:During the past week, I felt that everything I did was an effort.")
label("ces_5r_dichot","CES-D dichotomus:During the past week, I felt hopeful about the future.")
label("ces_6_dichot","CES-D dichotomus:During the past week, I felt fearful.")
label("ces_7_dichot","CES-D dichotomus:During the past week, my sleep was restless.")
label("ces_8r_dichot","CES-D dichotomus:During the past week, I was happy.")
label("ces_9_dichot","CES-D dichotomus:During the past week, I felt lonely.")
label("ces_10_dichot","CES-D dichotomus:During the past week, I could not get going.")
label("ces_dichot_total","CES-D dichotomus total")

#interpersonal support evaluation list
label("is_1r","Reverse trip for a day")
label("is_2r","Reverse no one to share worries")
label("is_7r","Reverse don't often get invited")
label("is_8r","Reverse difficult to find home sitter")
label("is_11r","Reverse difficult to find good advice")
label("is_12r","Reverse no help moving")
label("iseapp","ISE appraisal")
label("isebel","ISE belonging")
label("isetan","ISE tangable")

#Luben social network scale
label("lsn_family","Sum LSN_V1_family 0-15 (scores of less than 6 are considered to have marginal family ties")
label("lsn_friends","Sum LSN_V1_total 0-30 ((scores of less than 6 are considered to have marginal friendship ties")
label("lsn_total","Sum LSN_V1_total 0-30 (a score of 12 and lower delineates “at-risk” for social isolation and higher scores indicate more social engagement")

label("dd_total","Sum Detroit Day Discriminatio")
label("ptsd_total","Sum PTSD total")

label("weight_kg","Weight kilograms")
label("height_meter","Height meters")
label("height_meter_sq","Height meter squared")
label("bmi","Body mass index")

label("friends_smoke","Ratio of close friends who smoke for baseline")
label("time_to_complete","Finish time minus start time")


label("t_5val","How often do you smoke cigarettes or cigarillos?")
label("t_6val","In the last 24 hours, how many cigarettes or cigarillos have you smoked?")

#Vaccine
label("vac_2","You stated that you received a COVID-19 vaccine. What was the date that you received the first (or only) dose (if you do not remember the exact date, please provide your best estimate).")
label("vac_3","You stated that you received a COVID-19 vaccine. What was the date that you received the second dose (if you do not remember the exact date, please provide your best estimate).")

#MacArthur Major Discrimination
label("mmd_1a","How many times in your life have you been discriminated against by being discouraged by a teacher or advisor from seeking higher education because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")
label("mmd_1b","How many times in your life have you been discriminated against by being denied a scholarship because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")
label("mmd_1c","How many times in your life have you been discriminated against by not being hired for a job because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")
label("mmd_1d","How many times in your life have you been discriminated against by not receiving a job promotion because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")
label("mmd_1e","How many times in your life have you been discriminated against by being fired because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")
label("mmd_1f","How many times in your life have you been discriminated against by being prevented from renting or buying a home in the neighborhood you wanted because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")
label("mmd_1g","How many times in your life have you been discriminated against by being prevented from remaining in neighborhood because neighbors made life so uncomfortable because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")
label("mmd_1h","How many times in your life have you been discriminated against by being hassled by the police because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")
label("mmd_1i","How many times in your life have you been discriminated against by being denied a bank loan because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")
label("mmd_1j","How many times in your life have you been discriminated against by being denied or provided inferior medical care because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")
label("mmd_1k","How many times in your life have you been discriminated against by being denied or provided inferior service by a plumber, car mechanic, or other service provider because of such things as your race, ethnicity, gender, age, religion, physical appearance, sexual orientation, or other characteristics?")

#COVID Vaccine
label("vac_2y","Covid-19 vaccine year")
label("vac_2m","Covid-19 vaccine year")
label("vac_2d","Covid-19 vaccine year")
label("vac_3y","Covid-19 vaccine year")
label("vac_3m","Covid-19 vaccine year")
label("vac_3d","Covid-19 vaccine year")


label("tcu_ds_total","Sum TCU Desire for help subscale (888 indicates they have not used drugs in past 12 months")
label("tcu_ds_score","Score TCU Desire for help subscale")


label("pbq_v_2_total","Personality Beliefs Questionaire-Short Form- Antisocial Beliefs visit 2 Total")

label("tcu_desire_v_2_total","Sum, TCU Desire for help subscale (888 indicates they have not used drugs in past 12 months")
label("tcu_tn_v_2_total","Sum, TCU Treatment needs subscale")
label("tcu_ts_v_2_total","Sum, TCU treatment satisfaction subscale")
label("cj_21r","You feel like a failure recoded")
label("cj_22r","You wish you had more respect for yourself recoded")
label("cj_23r","You feel you are basically no good recoded")
label("cj_25r","You feel you are unimportant to others recoded")
label("tcu_se_v_2_total","Sum, TCU self esteem subscale")
label("tcu_hs_v_2_total","Sum, TCU hostility subscale")
label("cj_34r","You only do things that feel safe recoded")
label("cj_35r","You avoid anything dangerous recoded")
label("cj_36r","You are very careful and cautious recoded")
label("tcu_rt_v_2_total","Sum, TCU risk taking subscale")

label("mmd_total","MacArthur Major Discrimination total score")
label("uls_total","urban life stress total score")

#Perceived stress scale reverse code
label("ps_2r","Perceived Stress Scale Item 2 Reverse Code")
label("ps_3r","Perceived Stress Scale Item 3 Reverse Code")
label("ps_total","Perceived Stress Scale total score")

#Distress tolerance scale reverse code
label("dts_1r","Feeling distressed or upset is unbearable to me - Reverse coded")
label("dts_2r","When I feel distressed or upset, all I can think about is how bad I feel - Reverse coded")
label("dts_3r","I can’t handle feeling distressed or upset - Reverse coded")
label("dts_4r","My feelings of distress are so intense that they completely take over - Reverse coded")
label("dts_5r","There’s nothing worse than feeling distressed or upset - Reverse coded")
label("dts_6r","My feelings of distress or being upset are just an acceptable part of life - Reverse coded")
label("dts_8r","My feelings of distress or being upset are not acceptable - Reverse coded")
label("dts_9r","I’ll do anything to avoid feeling distressed or upset - Reverse coded")
label("dts_10r","Other people seem to be able to tolerate feeling distressed or upset better than I can - Reverse coded")
label("dts_11r","Being distressed or upset is always a major ordeal for me - Reverse coded")
label("dts_12r","I am ashamed of myself when I feel distressed or upset - Reverse coded")
label("dts_13r","My feelings of distress or being upset scare me - Reverse coded")
label("dts_14r","I’ll do anything to stop feeling distressed or upset - Reverse coded")
label("dts_15r","When I feel distressed or upset, I must do something about it immediately - Reverse coded")
label("dts_16r","When I feel distressed or upset, I cannot help but concentrate on how bad the distress actually feels - Reverse coded")
label("dts_tolerance","DTS Tolerance  subscale mean total")
label("dts_absorption","DTS absorption subscale mean total")
label("dts_appraisal","DTS appraisal subscale mean total")
label("dts_regulation","DTS regulation subscale mean total")
label("dts_total","Distress Tolerance Scale total score")

#Treatment Quality and Satisfaction Survey
label("tq_15_3","What do you like about the Link2Care smart phone application?")
label("tq_16_3","What do you not like about the Link2Care smart phone application?")
label("tq_17_3","How would you improve the Link2Care smart phone application?")
label("tq_18_3","What other thoughts and opinions do you have about the Link2Care application?")

#Heaviness of Smoking Index
label("hsi","Heaviness of Smoking Index score")

label("tcu_tn_v_4_total","Sum, TCU Treatment needs subscale Visit 4")
label("tcu_ts_total","Sum, TCU hostility subscale")

#REDcap
label("check_in_timestamp","Redcap check in time")
label("email","Redcap email")
label("consent_form_timestamp","Redcap consent form time")
label("consent_sig","Redcap consent form signature")
label("consent_date","Recap date of consent")
label("screening_timestamp","Redcap screening time")
label("sq_7b2","Redcap Ask individual if they have a study flyer from the Dallas County Jail? If they have a flyer insert number below, otherwise click not applicable")
label("demographic_information_timestamp","Redcap Demographic information time")
label("brief_homelessness_questionnaire_timestamp","Redcap Brief Homelessness Questionnaire time")
label("macarthur_scale_timestamp","Redcap Macarthur Scle time")
label("patient_health_questionnaire_timestamp","Redcap Patient health questionnaire time")
label("sf12_health_survey_timestamp","Redcap Health survey time")
label("health_related_quality_of_life_timestamp","Redcap Health related quality of life time")
label("selfrated_health_questionnaire_timestamp","Redcap Self-rated health questionnaire time ")
label("tcu_drug_screen_5_timestamp","Redcap TCU drug screen time")
label("pcptsd_screen_timestamp","Redcap PTSD screen time")
label("brfs_ace_module_timestamp","Redcap BRFSS Adverse Childhood Experience Model time")
label("tobacco_history_timestamp","Redcap Tobacco history questionnaire time")
label("brfss_inadequate_sleep_timestamp","Redcap BRFSS inadquate sleep time")
label("alcohol_quantity_and_frequency_timestamp","Redcap Alcohol Quantity, Frequency and Binge Drinking Questionnaire time")
label("personality_beliefs_questionnaire_timestamp","Redcap Personality Beliefs Questionaire time")
label("personality_beliefs_questionnaire_timestamp","Redcap Personality Beliefs Questionaire time")
label("usda_food_insecurity_survey_timestamp","Redcap USDA food insecurity survey time")
label("usda_food_insecurity_survey_timestamp","Redcap USDA food insecurity survey time")
label("meal_survey_timestamp","Redcap Meal Survey time")
label("tcu_client_evaluation_timestamp","Redcap TCU client evaluation time")
label("sexual_behaviors_timestamp","Redcap Sexual Behaviors time")
label("covid19_vaccine_timestamp","Redcap COVID 19 vaccine time")
label("detroit_area_study_assessment_timestamp","Redcap Detroit area study time")
label("macarthur_major_discrimination_timestamp","Redcap Macarthur major discrimination time")
label("urban_life_stressor_scale_timestamp","Redcap Urban life stressor scale time")
label("personal_victimization_timestamp","Redcap Personal victimization time")
label("perceived_stress_scale_timestamp","Redcap Perceived stress scale time")
label("distress_tolerance_scale_timestamp","Redcap Distress tolerance scale time")
label("negative_affect_aggression_aq12_timestamp","Redcap Negative affect agression time ")
label("cesd_timestamp","Redcap CES time")
label("interpersonal_support_evaluation_list_timestamp","Redcap Interpersonal support evaluation time")
label("religious_participation_timestamp","Redcap Religious participation time ")
label("lubben_social_network_scale_timestamp","Redcap Lubben social network scale time")
label("resource_utilization_questionnaire_timestamp","Redcap Resource utilization questionnaire time")
label("barriers_to_phone_based_case_management_timestamp","Redcap Barriers to phone based case management time")
label("treatment_and_quality_satisfaction_survey_timestamp","Redcap Treatment and quality satisfaction survey time")
label("staff_perceptions_of_the_link2care_app_timestamp","Redcap Staff perceptions of the Link2Care app time")

#TLFBs
label("days_followed","TLFB total days followed")
label("total_drinks","Total drinks")
label("num_drinking_days","Number of days drinking")
label("ave_drinks_day","Average drinks per day")
label("num_alc_abstinent_days","Number of abstinent days")
label("heavy_drinking_days","Heavy drinking days")
label("greatest_drinks_1_day","Greatest number of drinks in 1 day")
label("drinks_wk","Drinks per week")
label("num_days_using_drugs","Number of days using drugs")
label("per_days_using_drugs","Percentage of days using drugs")
label("per_drug_abstinent_days","Percentage of abstinent days")
label("drug_use_days_yr","Estimated drug use days per year")
label("drug_use_days_week","Average drug use days per week")
label("num_days_homeless","Number of days homeless")
label("per_days_homeless","Percentage of days homeless")
label("num_days_home","Number of days at home")
label("est_days_homeless_yr","Estimated number of days homeless per year")
label("avg_days_homeless_wk","Average number of days homeless per week")
label("flag_out_of_window","Flag visit out of window")

#Arrest data
label("arrested","Arrested Yes or No")
label("arrested_date_baseline","Arrest data: Participant baseline date")
label("arrested_date_1","1st arrested date")
label("arrested_date_2","2nd arrested date")
label("arrested_date_3","3rd arrested date")
label("arrested_date_4","4th arrested date")
label("arrested_date_5","5th arrested date")

#Bridge case manager sessions
label("bridge_baseline_date","Bridge Case manager sessions: Participant baseline date")
label("bridge_v2_rand_date","Bridge Case manager sessions: Randomized date")
label("bridge_v5_sched_final_visit_date","Bridge Case manager sessions: Visit 5 date")
label("bridge_date_session","Date of Bridge session")
label("bridge_type","Type of Bridge session")
label("bridge_duration","Duration of Bridge session")
label("bridge_flag_ns_v2","Bridge session no show V2")
label("bridge_flag_dropped","Bridge session dropped")
label("bridge_notes","Bridge session notes")
label("n_missing","Bridge session missing")
label("bridge_type_f","Case management")
label("bridge_case_management","dummy variable case management")
label("bridge_row","Bridge session row number")
label("bridge_total_sessions","Sum type of Bridge session")
label("bridge_total_minutes","Sum duration of bridge session")
label("bridge_any_case_management","Used at least one session of regular case management")
label("bridge_any_crisis_management","Used at least one session of crisis case management")
label("bridge_any_other","Used at least one session of other case management")
label("bridge_all_none","Used no forms of Bridge case management")

#DDT
label("ddt_k","DDT K")
label("ddt_ed50","DDT ED50")

```



