---
title: "Notes on changing the QDS column names"
date: "2021-07-17 <br> Updated: `r Sys.Date()`"
output: github_document
---


Why change the demographics variable names?
Why change the demographics column names one data set at a time? - This one I may not want to do....
Why do you need the codebooks?
How will you future proof this process?

In order to combine all 5 individual QDS data sets into one, we first needed to make many changes to the column names. We tried several different ways of doing so. The notes below document what we tried and how we arrived at our final solution. The purpose of this document is to make our research process as transparent as possible and to prevent us from trying a strategy at some point in the future that we've already tried. 

**Why can't we just combine them into one without making any changes to column names?**

There are intentional differences (e.g., "TODAY_V1" and "TODAY_V2") and unintentional errors (e.g., HEIGHT_3 instead of HEIGHT_V3) in the column names from data frame to data frame that make combining them without any alterations impossible.

**Why not just remove _V1, _V3, etc. and that's it?**

If we ONLY remove _V1, _V2, _V3, etc. from the column names, then we end up with duplicate column names. For example, T31B_V1 and T31_V1B both become T31B. 

We can "fix" these duplicate column names by manually changing them; however, it isn't clear what the best fix is. We can't rename T31_V1B T32_V1 because there is already a T32_V1 that would just create a new pair of duplicate column names. We could arbitrarily rename it something that isn't currently being used, but then it no longer flows with the rest of the colmn names for that section. 

Currently, our solution is to just rename all columns with new sequential numbers. 

The downside is that this makes the current Word codebooks totally unusable. 

At first, my plan was to resist the urge to change them. My thought was that I wanted the column names in the combined QDS data to match the existing Word codebooks. Then I realized that none of the calculated variables will be in the codebook files anyway. Also, there isn't a codebook file for the combined survey data set. So, we can go ahead and rename variables in this file. We will either have to create a new codebook for the combined data or just live without one. 

What would happen if we just imported the raw QDS data with no calculated variables, reordered them using the codebooks, made only small changes necessary to merge the data sets, then cleaned and renamed them?

I tried just importing the raw QDS data (no calculated columns):
* Can't just copy and paste the column names into select because you get the weird "hide" button. May be be able to get rid of that by adding come section headers as comments. Not sure. 
* Can also pass a character vector of column names to select; however, that may not be very future proof. We'll play with it some more. This doesn't work because there are already differences between the column names in the codebook and the column names in the data (e.g., T26_V1 no longer exists in the data). Again, we can make changes here and there to get that code to work, but I think it's better to see all the code written out and just have one place to fix it or update it.

**Why scrape the codebooks?**

We have to make the column names match across visits so that we can merge all of the individual QDS data frames into one.

The columns in the data are not arranged in the order that they exist in the actual QDS survey for some reason. This makes the data harder to work with, and it will make the codebook we eventually create difficult to use. So, we are going to reorder them. To prevent us from typing out 810 column names manually, we are going to read-in the column names from the codebook and then create a blog of text that we copy and paste into a code chunk using `select()` below. Prepping the codebook to be able to do this took a long time and isn't very future-proof. However, we should only have to do this step once. As changes occur to QDS in the future, we can just update the code chunk with the `select()` function.


**Why/why not make an Excel Crosswalk?**
Pros: 
* Everyone can use Excel. Not everyone is comfortable using RStudio. So, people other than me may be intimidated if they need to look up the changes to the variable names by opening an Rmd file in RStudio.   
* If I need to look up changes to varible names, it may be faster to do so in Excel.    

Cons:
* More work to create the Excel sheet.   
* Additional documents to keep track of and update. However, if ALL of the updates go in this file, then it should really be the only one that requires tracking and updating.    
* Hard to use versioning for Excel. Should be able to with CSV though.    


For now, I'm just going to go ahead and add the names to `select()` like I did with QDS. I may change this at some point in the future. 